// app/src/pages/TreinoDetalhe.vue
<script setup>
import { ref, computed } from "vue";
import { useRoute, useRouter } from "vue-router";
import { treinos } from "../data/mockData";
import { Card, IntervaloFlow, StatusBadge, PrimaryButton, TeamBadge } from "../components/ui";
import Icon from "../components/Icon.vue";
import { session } from "../stores/session";

function formatDateTime(iso) {
  if (!iso) return "-";
  const d = new Date(iso);
  return `${String(d.getDate()).padStart(2, "0")}/${String(d.getMonth() + 1).padStart(2, "0")} às ${String(
    d.getHours(),
  ).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`;
}

function deviationLabel(planejado, executado) {
  const diff = executado - planejado;
  const sign = diff > 0 ? "+" : "";
  const color = Math.abs(diff) <= 1 ? "text-secondary" : Math.abs(diff) <= 3 ? "text-warning" : "text-primary-text";
  return { text: `${sign}${diff} min`, color };
}

const impactStyles = {
  Baixo: "bg-secondary/15 text-secondary",
  Médio: "bg-warning/15 text-warning",
  Alto: "bg-primary/15 text-primary-text",
};

const route = useRoute();
const router = useRouter();

const role = computed(() => session.user?.role);
const canEdit = computed(() => role.value !== "responsavel");
const treino = computed(() => treinos.find((t) => t.id === route.params.id) ?? treinos[0]);
const plano = computed(() => treino.value.plano);
const sumula = computed(() => treino.value.sumula);
const executionLog = computed(() => treino.value.executionLog);
const totalPlanejado = computed(
  () =>
    plano.value.etapaInicial.duracaoMin +
    plano.value.etapaFundamentacao.duracaoMin +
    plano.value.etapaPrincipal.duracaoMin,
);

const sessionDateShort = computed(() => plano.value.sessionDate.split("-").reverse().slice(0, 2).join("/"));

const execRows = computed(() => {
  if (!executionLog.value) return [];
  return [
    { label: "Etapa Inicial (Aquecimento)", data: executionLog.value.etapaInicial },
    { label: "Etapa de Fundamentação", data: executionLog.value.etapaFundamentacao },
    { label: "Etapa Principal", data: executionLog.value.etapaPrincipal },
  ].map((r) => ({ ...r, dev: deviationLabel(r.data.planejadoMin, r.data.executadoMin) }));
});

const status = ref(null);

function handleExport() {
  status.value = "Relatório exportado (PDF) — download simulado para este wireframe.";
}

async function handleShare() {
  const link = typeof window !== "undefined" ? window.location.href : "";
  try {
    await navigator.clipboard?.writeText(link);
    status.value = "Link copiado para a área de transferência.";
  } catch {
    status.value = `Link: ${link}`;
  }
}
</script>

<template>
  <div class="flex flex-col gap-6">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
      <div class="flex items-center gap-3">
        <router-link
          to="/"
          class="rounded-lg border border-line p-2 text-ink-muted hover:bg-surface-2"
          aria-label="Voltar ao dashboard"
        >
          <Icon name="arrowLeft" class="h-4 w-4" />
        </router-link>
        <div>
          <h1 class="font-heading text-lg font-semibold text-ink sm:text-xl">
            Treino: {{ sessionDateShort }} · {{ treino.categoria }} ·
            {{ treino.turma }} · {{ treino.coachName }}
          </h1>
        </div>
      </div>
      <div v-if="canEdit" class="flex flex-wrap gap-2">
        <PrimaryButton variant="secondary" @click="router.push('/planos/novo')">
          <Icon name="edit" class="h-4 w-4" /> Editar
        </PrimaryButton>
        <PrimaryButton variant="secondary" @click="handleExport">
          <Icon name="download" class="h-4 w-4" /> Exportar
        </PrimaryButton>
        <PrimaryButton variant="secondary" @click="handleShare">
          <Icon name="share" class="h-4 w-4" /> Compartilhar
        </PrimaryButton>
      </div>
    </div>

    <p
      v-if="status"
      role="status"
      class="flex items-center gap-1.5 rounded-xl border border-secondary/30 bg-secondary/10 px-3 py-2 text-sm text-secondary"
    >
      <Icon name="check" class="h-4 w-4" /> {{ status }}
    </p>

    <!-- Seção 1: Plano -->
    <Card title="Seção 1 · Plano de Aula">
      <template #icon><Icon name="clipboard" class="h-4 w-4" /></template>
      <div class="mb-3 flex flex-wrap items-center gap-2 text-sm">
        <StatusBadge :status="plano.status" />
        <span v-if="plano.approvedAt" class="text-ink-muted">
          {{ formatDateTime(plano.approvedAt) }} por {{ plano.approvedBy }}
        </span>
        <span class="ml-auto rounded-full bg-primary/15 px-2.5 py-0.5 text-xs font-medium text-primary-text">
          Fase: {{ plano.fase }}
        </span>
      </div>

      <div
        v-if="plano.status === 'changes_requested' && plano.reviewComment"
        class="mb-3 flex items-start gap-2.5 rounded-xl border border-warning/40 bg-warning/10 p-3"
      >
        <Icon name="alert" class="mt-0.5 h-4 w-4 shrink-0 text-warning" />
        <div class="min-w-0 text-sm">
          <p class="font-semibold text-warning">Ajustes solicitados pelo Head Coach</p>
          <p class="mt-0.5 text-ink">{{ plano.reviewComment }}</p>
          <p v-if="plano.reviewedBy" class="mt-1 text-xs text-ink-muted">
            {{ plano.reviewedBy }}{{ plano.reviewedAt ? ` · ${formatDateTime(plano.reviewedAt)}` : "" }}
          </p>
        </div>
      </div>

      <p class="mb-1 text-sm text-ink-muted">
        <span class="font-medium text-ink">Tema:</span> {{ plano.tema }} · <span class="font-medium text-ink">Subtema:</span>
        {{ plano.subtema }} · <span class="font-medium text-ink">Horário:</span> {{ plano.horario }}
      </p>
      <p class="mb-3 text-sm text-ink-muted">
        <span class="font-medium text-ink">Período:</span> {{ plano.periodo }} · <span class="font-medium text-ink">Semana:</span>
        {{ plano.semana }}
      </p>

      <div class="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
        <div class="rounded-xl border border-line-soft bg-surface-2 p-3">
          <p class="text-sm font-semibold text-ink">
            Etapa Inicial (Aquecimento) — {{ plano.etapaInicial.duracaoMin }} min
          </p>
          <p class="mt-1 text-sm text-ink-muted">Objetivo: {{ plano.etapaInicial.objetivo }}</p>
          <p class="mt-2 text-sm font-medium text-ink">Estação 1 — {{ plano.etapaInicial.estacao1.nome }}</p>
          <p class="text-sm text-ink-muted">
            {{ plano.etapaInicial.estacao1.tipo }} · {{ plano.etapaInicial.estacao1.duracaoMin }} min · {{ plano.etapaInicial.estacao1.descricao }}
          </p>
          <p class="text-sm text-ink-muted">Materiais: {{ plano.etapaInicial.estacao1.materiais }}</p>
          <p class="mt-2 text-sm font-medium text-ink">Estação 2 — {{ plano.etapaInicial.estacao2.nome }}</p>
          <p class="text-sm text-ink-muted">
            {{ plano.etapaInicial.estacao2.tipo }} · {{ plano.etapaInicial.estacao2.duracaoMin }} min · {{ plano.etapaInicial.estacao2.descricao }}
          </p>
          <p class="text-sm text-ink-muted">Materiais: {{ plano.etapaInicial.estacao2.materiais }}</p>
        </div>
        <div class="rounded-xl border border-line-soft bg-surface-2 p-3">
          <p class="text-sm font-semibold text-ink">
            Etapa de Fundamentação — {{ plano.etapaFundamentacao.duracaoMin }} min
          </p>
          <p class="mt-1 text-sm text-ink-muted">Objetivo: {{ plano.etapaFundamentacao.objetivo }}</p>
          <p class="text-sm text-ink-muted">Tipo: {{ plano.etapaFundamentacao.tipo }}</p>
        </div>
        <div class="rounded-xl border border-line-soft bg-surface-2 p-3">
          <p class="text-sm font-semibold text-ink">
            Etapa Principal — {{ plano.etapaPrincipal.duracaoMin }} min
          </p>
          <p class="mt-1 text-sm text-ink-muted">Objetivo: {{ plano.etapaPrincipal.objetivo }}</p>
          <p class="text-sm text-ink-muted">Sub-temas: {{ plano.etapaPrincipal.subTemas.join(", ") }}</p>
          <p class="text-sm text-ink-muted">Orientações: {{ plano.etapaPrincipal.orientacoes.join(", ") }}</p>
          <p class="mb-1 mt-2 text-sm text-ink-muted">Protocolo de Intervalo:</p>
          <IntervaloFlow />
          <p class="mt-2 text-sm text-ink-muted">
            Hidratação {{ plano.etapaPrincipal.intervalo.hidratacaoMin }}min, Repouso
            {{ plano.etapaPrincipal.intervalo.repousoMin }}min, Instruir {{ plano.etapaPrincipal.intervalo.instruirMin }}min,
            Ativar {{ plano.etapaPrincipal.intervalo.ativarMin }}min
          </p>
        </div>
      </div>
      <p class="mt-3 text-sm font-semibold text-ink">Total Planejado: {{ totalPlanejado }} minutos</p>
    </Card>

    <!-- Seção 2: Súmula -->
    <Card title="Seção 2 · Súmula">
      <template #icon><Icon name="ball" class="h-4 w-4" /></template>
      <template v-if="canEdit" #headerAction>
        <PrimaryButton variant="secondary" @click="router.push('/sumulas/novo')">
          <Icon name="edit" class="h-4 w-4" /> Editar Escalação
        </PrimaryButton>
      </template>
      <div class="mb-3 flex flex-wrap items-center gap-2 text-sm">
        <StatusBadge :status="sumula.status" />
        <TeamBadge :team="sumula.team" />
        <span v-if="sumula.confirmedAt" class="text-ink-muted">{{ formatDateTime(sumula.confirmedAt) }}</span>
        <span class="ml-auto text-ink-muted">Escalação: {{ sumula.entries.length }} atletas</span>
      </div>
      <!-- Mobile (<640px): lista de cards em vez da tabela min-w-[480px]. -->
      <ul class="flex flex-col gap-2 sm:hidden">
        <li
          v-for="e in sumula.entries"
          :key="e.jersey"
          data-testid="sumula-entry-card"
          class="rounded-xl border border-line-soft bg-surface-2 p-3 text-sm"
        >
          <div class="flex items-center justify-between gap-2">
            <p class="font-semibold text-ink">
              Colete {{ e.jersey }} — {{ e.nome }}
            </p>
            <span class="shrink-0 text-secondary" :aria-label="e.starter ? 'Titular' : 'Reserva'">
              <Icon v-if="e.starter" name="check" class="h-4 w-4" />
              <span v-else class="text-ink-muted">—</span>
            </span>
          </div>
          <p class="mt-1 text-ink-muted">Posição: {{ e.posicao }}</p>
        </li>
      </ul>

      <!-- Tablet/desktop (≥640px): tabela completa, scroll horizontal contido. -->
      <div class="hidden overflow-x-auto overscroll-x-contain sm:block">
        <table class="w-full min-w-[480px] border-collapse text-sm">
          <thead>
            <tr class="border-b border-line text-left text-xs font-semibold uppercase tracking-wide text-ink-muted">
              <th scope="col" class="px-3 py-2">Número do Colete</th>
              <th scope="col" class="px-3 py-2">Nome</th>
              <th scope="col" class="px-3 py-2">Posição</th>
              <th scope="col" class="px-3 py-2">Titular</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="(e, i) in sumula.entries"
              :key="e.jersey"
              class="border-b border-line-soft last:border-0"
              :class="i % 2 === 1 ? 'bg-surface-2/40' : ''"
            >
              <td class="px-3 py-2 font-medium text-ink">{{ e.jersey }}</td>
              <td class="px-3 py-2 text-ink-muted">{{ e.nome }}</td>
              <td class="px-3 py-2 text-ink-muted">{{ e.posicao }}</td>
              <td class="px-3 py-2 text-secondary" :aria-label="e.starter ? 'Titular' : 'Reserva'">
                <Icon v-if="e.starter" name="check" class="h-4 w-4" />
                <template v-else>—</template>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </Card>

    <!-- Seção 3: Registro de Execução -->
    <Card v-if="executionLog" title="Seção 3 · Registro de Execução">
      <template #icon><Icon name="barChart" class="h-4 w-4" /></template>
      <div class="mb-3 flex flex-wrap items-center gap-2 text-sm">
        <StatusBadge :status="executionLog.status" />
        <span v-if="executionLog.confirmedAt" class="text-ink-muted">{{ formatDateTime(executionLog.confirmedAt) }}</span>
      </div>

      <div class="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
        <div v-for="row in execRows" :key="row.label" class="rounded-xl border border-line-soft bg-surface-2 p-3">
          <p class="text-sm font-semibold text-ink">{{ row.label }}</p>
          <p class="mt-1 text-sm text-ink-muted">
            Planejado: {{ row.data.planejadoMin }} min &nbsp;·&nbsp; Executado: {{ row.data.executadoMin }} min &nbsp;·&nbsp;
            <span class="font-semibold" :class="row.dev.color">{{ row.dev.text }}</span>
          </p>
          <p class="text-sm text-ink-muted">Observações: {{ row.data.observacoes }}</p>
        </div>
      </div>

      <div class="mt-4">
        <p class="mb-2 flex items-center gap-1.5 text-sm font-semibold text-ink">
          <Icon name="alert" class="h-4 w-4 text-warning" /> Desvios Registrados
        </p>
        <ul class="flex flex-col gap-2">
          <li
            v-for="d in executionLog.desvios"
            :key="d.id"
            class="flex items-start gap-2 rounded-xl border border-line-soft bg-surface-2 p-3 text-sm"
          >
            <span class="shrink-0 rounded-full px-2 py-0.5 text-xs font-medium" :class="impactStyles[d.impacto]">
              {{ d.impacto }}
            </span>
            <div>
              <p class="font-medium text-ink">Etapa {{ d.etapa }}</p>
              <p class="text-ink-muted">"{{ d.descricao }}"</p>
            </div>
          </li>
        </ul>
      </div>
    </Card>
    <Card v-else title="Seção 3 · Registro de Execução">
      <template #icon><Icon name="barChart" class="h-4 w-4" /></template>
      <p class="text-sm text-ink-muted">Execução ainda não registrada para este treino.</p>
    </Card>

    <!-- Seção 4: Avaliação -->
    <Card v-if="executionLog" title="Seção 4 · Avaliação">
      <template #icon><Icon name="lineChart" class="h-4 w-4" /></template>
      <p class="flex items-start gap-2 text-sm text-ink-muted">
        <Icon name="alert" class="mt-0.5 h-4 w-4 shrink-0 text-warning" />
        Avaliação pendente de metodologia definida pela coordenação pedagógica. Indicadores pedagógicos e
        metodologia de conformidade pendentes de validação.
      </p>

      <div class="mt-4 rounded-xl border border-line-soft bg-surface-2 p-3">
        <p class="mb-1 flex items-center gap-1.5 text-sm font-semibold text-ink">
          <Icon name="bot" class="h-4 w-4 text-primary" /> Inteligência Artificial
        </p>
        <p class="text-sm text-ink-muted">
          Área reservada para futuros insights de inteligência artificial, após definição dos indicadores e
          geração de uma base de dados confiável.
        </p>
      </div>

      <div v-if="canEdit" class="mt-4 flex flex-wrap gap-2">
        <PrimaryButton variant="secondary" @click="router.push('/planos/novo')">
          <Icon name="edit" class="h-4 w-4" /> Editar
        </PrimaryButton>
        <PrimaryButton variant="secondary" @click="handleExport">
          <Icon name="download" class="h-4 w-4" /> Exportar Relatório
        </PrimaryButton>
        <PrimaryButton variant="secondary" @click="handleShare">
          <Icon name="share" class="h-4 w-4" /> Compartilhar
        </PrimaryButton>
      </div>
    </Card>
  </div>
</template>

// app/src/pages/TreinoDetalhe.tsx
import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { treinos } from "../data/mockData";
import { Card, IntervaloFlow, StatusBadge, PrimaryButton } from "../components/ui";
import { Icon } from "../components/Icon";
import { useRole } from "../state/SessionContext";

function formatDateTime(iso?: string) {
  if (!iso) return "-";
  const d = new Date(iso);
  return `${String(d.getDate()).padStart(2, "0")}/${String(d.getMonth() + 1).padStart(2, "0")} às ${String(
    d.getHours(),
  ).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`;
}

function deviationLabel(planejado: number, executado: number) {
  const diff = executado - planejado;
  const sign = diff > 0 ? "+" : "";
  const color = Math.abs(diff) <= 1 ? "text-secondary" : Math.abs(diff) <= 3 ? "text-warning" : "text-primary-text";
  return { text: `${sign}${diff} min`, color };
}

const impactStyles: Record<string, string> = {
  Baixo: "bg-secondary/15 text-secondary",
  Médio: "bg-warning/15 text-warning",
  Alto: "bg-primary/15 text-primary-text",
};

export default function TreinoDetalhe() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { role } = useRole();
  const canEdit = role !== "responsavel";
  const treino = treinos.find((t) => t.id === id) ?? treinos[0];
  const { plano, sumula, executionLog } = treino;
  const totalPlanejado =
    plano.etapaInicial.duracaoMin + plano.etapaFundamentacao.duracaoMin + plano.etapaPrincipal.duracaoMin;

  const [status, setStatus] = useState<string | null>(null);

  function handleExport() {
    setStatus("Relatório exportado (PDF) — download simulado para este wireframe.");
  }

  async function handleShare() {
    const link = typeof window !== "undefined" ? window.location.href : "";
    try {
      await navigator.clipboard?.writeText(link);
      setStatus("Link copiado para a área de transferência.");
    } catch {
      setStatus(`Link: ${link}`);
    }
  }

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-3">
          <Link
            to="/"
            className="rounded-lg border border-line p-2 text-ink-muted hover:bg-surface-2"
            aria-label="Voltar ao dashboard"
          >
            <Icon name="arrowLeft" className="h-4 w-4" />
          </Link>
          <div>
            <h1 className="font-heading text-lg font-semibold text-ink sm:text-xl">
              Treino: {plano.sessionDate.split("-").reverse().slice(0, 2).join("/")} · {treino.categoria} ·{" "}
              {treino.turma} · {treino.coachName}
            </h1>
          </div>
        </div>
        {canEdit && (
          <div className="flex flex-wrap gap-2">
            <PrimaryButton variant="secondary" onClick={() => navigate("/planos/novo")}>
              <Icon name="edit" className="h-4 w-4" /> Editar
            </PrimaryButton>
            <PrimaryButton variant="secondary" onClick={handleExport}>
              <Icon name="download" className="h-4 w-4" /> Exportar
            </PrimaryButton>
            <PrimaryButton variant="secondary" onClick={handleShare}>
              <Icon name="share" className="h-4 w-4" /> Compartilhar
            </PrimaryButton>
          </div>
        )}
      </div>

      {status && (
        <p role="status" className="flex items-center gap-1.5 rounded-xl border border-secondary/30 bg-secondary/10 px-3 py-2 text-sm text-secondary">
          <Icon name="check" className="h-4 w-4" /> {status}
        </p>
      )}

      {/* Seção 1: Plano */}
      <Card title="Seção 1 · Plano de Aula" icon={<Icon name="clipboard" className="h-4 w-4" />}>
        <div className="mb-3 flex flex-wrap items-center gap-2 text-sm">
          <StatusBadge status={plano.status} />
          {plano.approvedAt && (
            <span className="text-ink-muted">
              {formatDateTime(plano.approvedAt)} por {plano.approvedBy}
            </span>
          )}
          <span className="ml-auto rounded-full bg-primary/15 px-2.5 py-0.5 text-xs font-medium text-primary-text">
            Fase: {plano.fase}
          </span>
        </div>

        <p className="mb-1 text-sm text-ink-muted">
          <span className="font-medium text-ink">Tema:</span> {plano.tema} · <span className="font-medium text-ink">Subtema:</span>{" "}
          {plano.subtema} · <span className="font-medium text-ink">Horário:</span> {plano.horario}
        </p>
        <p className="mb-3 text-sm text-ink-muted">
          <span className="font-medium text-ink">Período:</span> {plano.periodo} · <span className="font-medium text-ink">Semana:</span>{" "}
          {plano.semana}
        </p>

        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
          <div className="rounded-xl border border-line-soft bg-surface-2 p-3">
            <p className="text-sm font-semibold text-ink">
              Etapa Inicial (Aquecimento) — {plano.etapaInicial.duracaoMin} min
            </p>
            <p className="mt-1 text-sm text-ink-muted">Objetivo: {plano.etapaInicial.objetivo}</p>
            <p className="mt-2 text-sm font-medium text-ink">Estação 1 — {plano.etapaInicial.estacao1.nome}</p>
            <p className="text-sm text-ink-muted">
              {plano.etapaInicial.estacao1.tipo} · {plano.etapaInicial.estacao1.duracaoMin} min · {plano.etapaInicial.estacao1.descricao}
            </p>
            <p className="text-sm text-ink-muted">Materiais: {plano.etapaInicial.estacao1.materiais}</p>
            <p className="mt-2 text-sm font-medium text-ink">Estação 2 — {plano.etapaInicial.estacao2.nome}</p>
            <p className="text-sm text-ink-muted">
              {plano.etapaInicial.estacao2.tipo} · {plano.etapaInicial.estacao2.duracaoMin} min · {plano.etapaInicial.estacao2.descricao}
            </p>
            <p className="text-sm text-ink-muted">Materiais: {plano.etapaInicial.estacao2.materiais}</p>
          </div>
          <div className="rounded-xl border border-line-soft bg-surface-2 p-3">
            <p className="text-sm font-semibold text-ink">
              Etapa de Fundamentação — {plano.etapaFundamentacao.duracaoMin} min
            </p>
            <p className="mt-1 text-sm text-ink-muted">Objetivo: {plano.etapaFundamentacao.objetivo}</p>
            <p className="text-sm text-ink-muted">Tipo: {plano.etapaFundamentacao.tipo}</p>
          </div>
          <div className="rounded-xl border border-line-soft bg-surface-2 p-3">
            <p className="text-sm font-semibold text-ink">
              Etapa Principal — {plano.etapaPrincipal.duracaoMin} min
            </p>
            <p className="mt-1 text-sm text-ink-muted">Objetivo: {plano.etapaPrincipal.objetivo}</p>
            <p className="text-sm text-ink-muted">Sub-temas: {plano.etapaPrincipal.subTemas.join(", ")}</p>
            <p className="text-sm text-ink-muted">Orientações: {plano.etapaPrincipal.orientacoes.join(", ")}</p>
            <p className="mb-1 mt-2 text-sm text-ink-muted">Protocolo de Intervalo:</p>
            <IntervaloFlow />
            <p className="mt-2 text-sm text-ink-muted">
              Hidratação {plano.etapaPrincipal.intervalo.hidratacaoMin}min, Repouso{" "}
              {plano.etapaPrincipal.intervalo.repousoMin}min, Instruir {plano.etapaPrincipal.intervalo.instruirMin}min,
              Ativar {plano.etapaPrincipal.intervalo.ativarMin}min
            </p>
          </div>
        </div>
        <p className="mt-3 text-sm font-semibold text-ink">Total Planejado: {totalPlanejado} minutos</p>
      </Card>

      {/* Seção 2: Súmula */}
      <Card
        title="Seção 2 · Súmula"
        icon={<Icon name="ball" className="h-4 w-4" />}
        headerAction={
          canEdit ? (
            <PrimaryButton variant="secondary" onClick={() => navigate("/sumulas/novo")}>
              <Icon name="edit" className="h-4 w-4" /> Editar Escalação
            </PrimaryButton>
          ) : undefined
        }
      >
        <div className="mb-3 flex flex-wrap items-center gap-2 text-sm">
          <StatusBadge status={sumula.status} />
          {sumula.confirmedAt && <span className="text-ink-muted">{formatDateTime(sumula.confirmedAt)}</span>}
          <span className="ml-auto text-ink-muted">Escalação: {sumula.entries.length} atletas</span>
        </div>
        {/* Mobile (<640px): lista de cards em vez da tabela min-w-[480px]. */}
        <ul className="flex flex-col gap-2 sm:hidden">
          {sumula.entries.map((e) => (
            <li key={e.jersey} data-testid="sumula-entry-card" className="rounded-xl border border-line-soft bg-surface-2 p-3 text-sm">
              <div className="flex items-center justify-between gap-2">
                <p className="font-semibold text-ink">
                  Colete {e.jersey} — {e.nome}
                </p>
                <span className="shrink-0 text-secondary" aria-label={e.starter ? "Titular" : "Reserva"}>
                  {e.starter ? <Icon name="check" className="h-4 w-4" /> : <span className="text-ink-muted">—</span>}
                </span>
              </div>
              <p className="mt-1 text-ink-muted">Posição: {e.posicao}</p>
            </li>
          ))}
        </ul>

        {/* Tablet/desktop (≥640px): tabela completa, scroll horizontal contido. */}
        <div className="hidden overflow-x-auto overscroll-x-contain sm:block">
          <table className="w-full min-w-[480px] border-collapse text-sm">
            <thead>
              <tr className="border-b border-line text-left text-xs font-semibold uppercase tracking-wide text-ink-muted">
                <th scope="col" className="px-3 py-2">Número do Colete</th>
                <th scope="col" className="px-3 py-2">Nome</th>
                <th scope="col" className="px-3 py-2">Posição</th>
                <th scope="col" className="px-3 py-2">Titular</th>
              </tr>
            </thead>
            <tbody>
              {sumula.entries.map((e, i) => (
                <tr key={e.jersey} className={`border-b border-line-soft last:border-0 ${i % 2 === 1 ? "bg-surface-2/40" : ""}`}>
                  <td className="px-3 py-2 font-medium text-ink">{e.jersey}</td>
                  <td className="px-3 py-2 text-ink-muted">{e.nome}</td>
                  <td className="px-3 py-2 text-ink-muted">{e.posicao}</td>
                  <td className="px-3 py-2 text-secondary" aria-label={e.starter ? "Titular" : "Reserva"}>
                    {e.starter ? <Icon name="check" className="h-4 w-4" /> : "—"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      {/* Seção 3: Registro de Execução */}
      {executionLog ? (
        <Card title="Seção 3 · Registro de Execução" icon={<Icon name="barChart" className="h-4 w-4" />}>
          <div className="mb-3 flex flex-wrap items-center gap-2 text-sm">
            <StatusBadge status={executionLog.status} />
            {executionLog.confirmedAt && <span className="text-ink-muted">{formatDateTime(executionLog.confirmedAt)}</span>}
          </div>

          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {[
              { label: "Etapa Inicial (Aquecimento)", data: executionLog.etapaInicial },
              { label: "Etapa de Fundamentação", data: executionLog.etapaFundamentacao },
              { label: "Etapa Principal", data: executionLog.etapaPrincipal },
            ].map(({ label, data }) => {
              const dev = deviationLabel(data.planejadoMin, data.executadoMin);
              return (
                <div key={label} className="rounded-xl border border-line-soft bg-surface-2 p-3">
                  <p className="text-sm font-semibold text-ink">{label}</p>
                  <p className="mt-1 text-sm text-ink-muted">
                    Planejado: {data.planejadoMin} min &nbsp;·&nbsp; Executado: {data.executadoMin} min &nbsp;·&nbsp;{" "}
                    <span className={`font-semibold ${dev.color}`}>{dev.text}</span>
                  </p>
                  <p className="text-sm text-ink-muted">Observações: {data.observacoes}</p>
                </div>
              );
            })}
          </div>

          <div className="mt-4">
            <p className="mb-2 flex items-center gap-1.5 text-sm font-semibold text-ink">
              <Icon name="alert" className="h-4 w-4 text-warning" /> Desvios Registrados
            </p>
            <ul className="flex flex-col gap-2">
              {executionLog.desvios.map((d) => (
                <li key={d.id} className="flex items-start gap-2 rounded-xl border border-line-soft bg-surface-2 p-3 text-sm">
                  <span className={`shrink-0 rounded-full px-2 py-0.5 text-xs font-medium ${impactStyles[d.impacto]}`}>
                    {d.impacto}
                  </span>
                  <div>
                    <p className="font-medium text-ink">Etapa {d.etapa}</p>
                    <p className="text-ink-muted">"{d.descricao}"</p>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        </Card>
      ) : (
        <Card title="Seção 3 · Registro de Execução" icon={<Icon name="barChart" className="h-4 w-4" />}>
          <p className="text-sm text-ink-muted">Execução ainda não registrada para este treino.</p>
        </Card>
      )}

      {/* Seção 4: Avaliação */}
      {executionLog && (
        <Card title="Seção 4 · Avaliação" icon={<Icon name="lineChart" className="h-4 w-4" />}>
          <p className="flex items-start gap-2 text-sm text-ink-muted">
            <Icon name="alert" className="mt-0.5 h-4 w-4 shrink-0 text-warning" />
            Avaliação pendente de metodologia definida pela coordenação pedagógica. Indicadores pedagógicos e
            metodologia de conformidade pendentes de validação.
          </p>

          <div className="mt-4 rounded-xl border border-line-soft bg-surface-2 p-3">
            <p className="mb-1 flex items-center gap-1.5 text-sm font-semibold text-ink">
              <Icon name="bot" className="h-4 w-4 text-primary" /> Inteligência Artificial
            </p>
            <p className="text-sm text-ink-muted">
              Área reservada para futuros insights de inteligência artificial, após definição dos indicadores e
              geração de uma base de dados confiável.
            </p>
          </div>

          {canEdit && (
            <div className="mt-4 flex flex-wrap gap-2">
              <PrimaryButton variant="secondary" onClick={() => navigate("/planos/novo")}>
                <Icon name="edit" className="h-4 w-4" /> Editar
              </PrimaryButton>
              <PrimaryButton variant="secondary" onClick={handleExport}>
                <Icon name="download" className="h-4 w-4" /> Exportar Relatório
              </PrimaryButton>
              <PrimaryButton variant="secondary" onClick={handleShare}>
                <Icon name="share" className="h-4 w-4" /> Compartilhar
              </PrimaryButton>
            </div>
          )}
        </Card>
      )}
    </div>
  );
}
